all queries written
MTechRnd/EfCoreJson pull request #6
Opened 2023-05-17 06:47 UTC by smitesh-maniya

all queries are written for traditional and JSON approach.

2023-05-18 06:16 UTC, goldytech requested changes
Work on feedback given

2023-05-18 06:16 UTC, goldytech commented on EFCoreJsonApp/EFCoreJsonApp.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
@smitesh-maniya Any specific reason for `Newtonsoft.Json` , We always prefer `System.Text.Json`

2023-05-18 06:16 UTC, goldytech commented on EFCoreJsonApp/Models/OrderDetails/OrderCount.cs
> +        public int totalOrder { get; set; }
@smitesh-maniya Please use PascalCase for property naming

2023-05-18 06:16 UTC, goldytech commented on EFCoreJsonApp/Services/JsonService/IJsonService.cs
> +        Task<IList<OrderWithOrderDetailEntity>> GetDataForMultipleCustomer(List<Guid> ids);
@smitesh-maniya Always use Abstraction for method parameters instead of `List` use `IList`

2023-05-18 06:16 UTC, goldytech commented on EFCoreJsonApp/Services/JsonService/JsonService.cs
> +            return (decimal)totalSum;
@smitesh-maniya Why type casting ???

2023-05-18 06:22 UTC, smitesh-maniya commented on EFCoreJsonApp/EFCoreJsonApp.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
I have added it for testing purposes.

2023-05-19 11:12 UTC, goldytech requested changes
Work on the changes

2023-05-19 11:12 UTC, goldytech commented on EFCoreJsonApp/Services/JsonService/JsonService.cs
> +        public async Task<decimal> AverageOfPrice()
@smitesh-maniya return the object `AverageOfPriceResult` instead of decimal

2023-05-19 11:17 UTC, smitesh-maniya commented on EFCoreJsonApp/Models/AggregateOperations/AverageOfPriceResult.cs
> +{
yes sir, without it we can not get aggregate results.

2023-05-19 11:20 UTC, smitesh-maniya commented on EFCoreJsonApp/Services/TraditionalService/ITraditionalService.cs
>      }
yes sir, i will add it.

2023-05-23 06:23 UTC, goldytech requested changes
@smitesh-maniya Work on the feedback given. Let me know if you have any questions.

2023-05-23 06:23 UTC, goldytech commented on EFCoreJsonApp/Models/AggregateOperations/MaxQuantityResult.cs
> +    public class MaxQuantityResult
@smitesh-maniya See if you can use Record here with a primary constructor instead of class

2023-05-23 06:23 UTC, goldytech commented on EFCoreJsonApp/Services/JsonService/JsonService.cs
> +                .Select(x => x.AverageOfPrice)
@smitesh-maniya I believe we already have selected columns in the SELECT raw query. I don't think the linq select expression is required, also remove `FirstOrDefaultAsync` 
Please don't use duplicate linq statements/ expressions which are already part of the SQL raw query.

2023-05-23 06:23 UTC, goldytech commented on EFCoreJsonApp/Services/JsonUsingLinqService/IJsonUsingLinqService.cs
> +        Task<IList<OrderWithOrderDetailEntity>> GetAllData();
Any method/function which returns `Task` or `Task<T>` should have suffix Async eg `GetAllDataAsync`

2023-05-23 06:23 UTC, goldytech commented on EFCoreJsonApp/Services/JsonUsingLinqService/JsonUsingLinqService.cs
> +                .AsEnumerable()
`.AsEnumerable` is required? The DbSet `OrderWithOrderDetails` is already `IQueryable`, so should support all linq methods.

2023-05-23 06:48 UTC, smitesh-maniya commented on EFCoreJsonApp/Models/AggregateOperations/MaxQuantityResult.cs
> +    public class MaxQuantityResult
Here I can not understand what you said.

2023-05-23 06:51 UTC, smitesh-maniya commented on EFCoreJsonApp/Models/AggregateOperations/MaxQuantityResult.cs
> +    public class MaxQuantityResult
Here I can not understand what you said. Can you please tell me more about this?

2023-05-23 07:06 UTC, smitesh-maniya commented on EFCoreJsonApp/Services/JsonService/JsonService.cs
> +                .Select(x => x.AverageOfPrice)
This raw query return me column so i used select linq for that and to get value i used firstOrDefault linq.

2023-06-26 12:16 UTC, merged